language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install selenium

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 http://localhost:80
before_script: cd tests
script: python test.py
